---
- name: Terraform | Download zip file
  get_url:
      url: "{{ terraform_url }}"
      dest: "/tmp/terraform_{{ terraform.version }}.zip"
      mode: 0664

- name: Terraform | Create unzip destination
  file:
      path: "/usr/local/terraform_{{ terraform.version }}"
      state: directory
      mode: 0755

- name: Terraform | Extract zip file
  unarchive:
      src: "{{ terraform_url }}"
      dest: "/usr/local/terraform_{{ terraform.version }}"
      remote_src: yes

- name: Terraform | Link terraform binary
  file:
      src: "/usr/local/terraform_{{ terraform.version }}/terraform"
      dest: "/usr/local/bin/terraform"
      state: link
